# This is a basic workflow to help you get started with Actions

name: start Node-pipeline

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo I'm starting!

      - name: Run Node Action
        uses: elisemjoen/testapp/.github/workflows/nodejs_build_test.yml@main
        with:
            example_input: "Hello"


      - run: echo Finished:)))
